#!/bin/sh

[ -z "${GH_TOKEN}" ] && exit 0
[ "${TRAVIS_BRANCH}" != "master" ] && exit 0

rm -rf gh-pages
git clone -b gh-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
cp -r _book/* gh-pages/
cd gh-pages
git add *
git commit -a -m"update homepage (travis build ${TRAVIS_BUILD_NUMBER})"
git push -q -f origin gh-pages
