#!/bin/sh

[ -z "${GH_TOKEN}" ] && exit 0
[ "${TRAVIS_BRANCH}" != "master" ] && exit 0

BOOK_DIR=$(pwd)/_book
rm -rf ~/_book
cd ~/_book
git clone -b gh-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git .
find . ! -name 'bookdown.pdf' ! -name '.nojekyll' -exec rm -rf {} +
cp -r ${BOOK_DIR}/* ./
git add --all *
git commit -m"update homepage (travis build ${TRAVIS_BUILD_NUMBER})"
git push -q -f origin gh-pages
