--- 
title: "Authoring A Book with R Markdown and bookdown"
author: "Yihui Xie"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
output:
  bookdown::html_chapters:
    css: style.css
    md_extensions: +markdown_in_html_blocks
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
  pdf_document:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    fig_caption: yes
  html_document:
    css: style.css
    fig_caption: yes
    keep_md: yes
    md_extensions: +markdown_in_html_blocks
    self_contained: yes
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Introduction

```{block, type='rmdwarning'}
This book and the package **bookdown** are still under active development, and should not be considered stable at the moment. You are welcome to experiment with this package, and feedback may be sent to yihui@rstudio.com.
```

This book is a guide to authoring books with R Markdown [@R-rmarkdown] and the R package **bookdown** [@R-bookdown]. It focuses on the features specific to writing books, long-form articles, or reports, such as

- How to typeset figures and tables, and cross-reference them;
- How to generate multiple output formats such as HTML, PDF, and E-Books for a single book;
- How to customize the book templates and style different elements in a book;
- The editor support (in particular, the RStudio IDE);
- How to publish a book;

It is not a comprehensive introduction to R Markdown or the **knitr** package, on top of which **bookdown** was built. To learn more about R Markdown, please check out the online documentation <http://rmarkdown.rstudio.com>. For **knitr**, please see @xie2015. You do not have to be an expert of the R language [@R-base] to read this book, but you are expected to have some basic knowledge about R Markdown and **knitr**. For beginners, you may get started with the cheetsheets at <https://www.rstudio.com/resources/cheatsheets/>. To be able to customize the book templates and themes, you should be familiar with LaTeX, HTML and CSS.

## Motivation



## Usage

A book normally contains multiple chapters. We assume that one chapter lives in one R Markdown file (with the filename extension `.Rmd`). You should not have multiple chapters in one R Markdown file, or one chapter split into multiple R Markdown files. Each R Markdown file must start immediately with the chapter title. Here is an example (the bullets are the filenames, followed by the file content):

- 01-intro.Rmd

    ```markdown
    # Introduction
    
    This chapter is an overview of the methods that
    we propose to solve an **important problem**.
    ```

- 02-literature.Rmd

    ```markdown
    # Literature
    
    Here is a review of existing methods.
    ```

- 03-method.Rmd

    ```markdown
    # Methods
    
    We describe our methods in this chapter.
    ```

- 04-application.Rmd

    ```markdown
    # Applications
    
    Some _significant_ applications are demonstrated
    in this chapter.
    
    ## Example one
    
    ## Example two
    ```

- 05-summary.Rmd

    ```markdown
    # Final Words
    
    We have finished a nice book.
    ```

By default, **bookdown** merges all Rmd files by the order of filenames, e.g., `01-intro.Rmd` will appear before `02-literature.Rmd`. Filenames that start with an underscore `_` are skipped. If there exists an Rmd file named `index.Rmd`, it will always be treated as the first file when merging all Rmd files. The reason for this special treatment is that the HTML file `index.html` to be generated from `index.Rmd` is usually the default index file when you view a website, e.g., you are actually browsing http://yihui.name/index.html when you open http://yihui.name/.

You can override the above behavior by including a configuration file named `_config.yml` in the book directory. It is a YAML file (https://en.wikipedia.org/wiki/YAML), and R Markdown users should be familiar with this format since it is also used to write the metadata in the beginning of R Markdown documents. You can use a field named `rmd_files` to define your own list and order of Rmd files for the book. For example,

```yaml
rmd_files: ["index.Rmd", "abstract.Rmd", "intro.Rmd"]
```

In this case, **bookdown** will just use whatever you defined in this YAML field without any special treatments of `index.Rmd` or underscores.

```{block, type='rmdimportant'}
Because **knitr** does not allow duplicate chunk labels in a source document, you need to make sure there are no duplicate labels in your book chapters, otherwise **knitr** will signal an error when knitting the merged Rmd file. 
```

At the moment, there are two output formats that you may use: `bookdown::pdf_book` and `bookdown::html_chapters`. There is a `bookdown::render_book()` function similar to `rmarkdown::render()` that renders multiple Rmd documents into a book using the output format functions. You may either call this function from command line, or use it in the RStudio IDE. Here are some command line examples:

```{r eval=FALSE}
bookdown::render_book('foo.Rmd', 'bookdown::html_chapters')
bookdown::render_book('foo.Rmd', 'bookdown::pdf_book')
bookdown::render_book('foo.Rmd', bookdown::html_chapters(lib_dir = 'book_assets'))
bookdown::render_book('foo.Rmd', bookdown::pdf_book(keep_tex = TRUE))
```

To use `render_book` and the output format functions in the RStudio IDE, you can define a YAML field named `knit` that takes the value `bookdown::render_book`, and the output format functions can be used in the `output` field, e.g.,

```yaml
---
knit: "bookdown::render_book"
output:
  bookdown::html_chapters:
    lib_dir: "book_assets"
  bookdown::pdf_book:
    keep_tex: yes
---
```

Then you can click the `Knit` button in RStudio to compile the Rmd files into a book.

